DROP TABLE IF EXISTS ODONTOLOGO; CREATE TABLE ODONTOLOGO (PRIMARY KEY, NUMERODEMATRICULA VARCHAR(50) NOT NULL, NOMBRE VARCHAR(50) NOT NULL, APELLIDO VARCHAR(50) NOT NULL);


-- para test --
INSERT INTO ODONTOLOGO(NUMERODEMATRICULA, NOMBRE, APELLIDO) VALUES ('Aw348C782k', 'Juancito', 'Martinez'), ('Mg86rf4h', 'Daniel', 'Perez');
